[package]
name = "pyo3_extension"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyo3_extension"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15", features = ["extension-module"] }
pyo3_lib = { path = "../pyo3_lib" }

[build-dependencies]
pyo3-build-config = "0.15"
